[package]
name = "cf-ws-v1"
version = "0.1.0"
authors = ["seanh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10.1"
futures = "0.1.28"
native-tls = "0.2.3"
openssl = "0.10.24"
serde_json = "1.0.40"
tokio = "0.1.22"
websocket = "0.23.0"
