[package]
name = "cf-ws-v1"
version = "0.1.0"
authors = ["seanh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10.1"
futures = "0.1.28"
log = "0.4.8"
native-tls = "0.2.3"
openssl = "0.10.24"
serde = {version = "1.0.98", features = ["derive"]}
serde_json = "1.0.40"
tokio = "0.1.22"
websocket = "0.23.0"

[dev-dependencies]
env_logger = "0.6.2"


[lib]
name = "cf_ws_v1"
path = "src/lib.rs"
